# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('delta_dump', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='current_turn_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameactor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='turn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c361.GameInstance'),
        ),
    ]
