# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0002_auto_20160228_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='id',
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
