# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0002_auto_20160302_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
