# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0003_gameinstance_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='active',
        ),
    ]
