# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0004_remove_gameinstance_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameActor',
            new_name='GameActorModel',
        ),
        migrations.RenameModel(
            old_name='GameInstance',
            new_name='GameInstanceModel',
        ),
        migrations.RenameModel(
            old_name='Turn',
            new_name='TurnModel',
        ),
    ]
