# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0005_auto_20160305_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactormodel',
            name='direction',
            field=models.CharField(default='North', max_length=20),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='hunger',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='is_sleeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='sleep',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='x_coord',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='y_coord',
            field=models.IntegerField(default=-1),
        ),
    ]
