# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0006_auto_20160305_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactormodel',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turnmodel',
            name='delta_dump',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='turnmodel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='c361.GameInstanceModel'),
        ),
    ]
