# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0008_gameinstancemodel_world'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameactormodel',
            name='food',
        ),
    ]
