# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0010_auto_20160323_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstancemodel',
            name='world',
        ),
        migrations.AddField(
            model_name='gameinstancemodel',
            name='cells',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameinstancemodel',
            name='seed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameactormodel',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='c361.GameActorModel'),
        ),
    ]
