# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0011_auto_20160323_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactormodel',
            name='has_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameactormodel',
            name='has_rock',
            field=models.BooleanField(default=False),
        ),
    ]
