# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0012_auto_20160324_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstancemodel',
            name='cells',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gameinstancemodel',
            name='seed',
            field=models.TextField(default=''),
        ),
    ]
