# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c361', '0013_auto_20160324_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnmodel',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='gameinstancemodel',
            old_name='current_turn_number',
            new_name='current_turn',
        ),
    ]
